<?php
/**
 * Eventogen Mailer - Installation Wizard
 *
 * Self-contained (does NOT load the app bootstrap, since config may not be
 * valid yet). Checks requirements, writes config/config.php, imports the
 * schema and creates the admin account.
 */

declare(strict_types=1);

error_reporting(E_ALL);
ini_set('display_errors', '1');

const ROOT = __DIR__ . '/../..';   // project root (this file lives in public/install)
const LOCK = ROOT . '/config/installed.lock';

if (is_file(LOCK)) {
    http_response_code(403);
    exit('Already installed. Delete config/installed.lock to re-run the installer.');
}

/* ---- requirement checks ------------------------------------------- */
$checks = [
    'PHP >= 8.1'          => version_compare(PHP_VERSION, '8.1.0', '>='),
    'PDO MySQL extension' => extension_loaded('pdo_mysql'),
    'OpenSSL extension'   => extension_loaded('openssl'),
    'mbstring extension'  => extension_loaded('mbstring'),
    'config/ writable'    => is_writable(ROOT . '/config'),
];
$canInstall = !in_array(false, $checks, true);

$errors = [];
$done = false;

/* ---- handle submit ------------------------------------------------ */
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $canInstall) {
    $dbHost = trim($_POST['db_host'] ?? 'localhost');
    $dbName = trim($_POST['db_name'] ?? '');
    $dbUser = trim($_POST['db_user'] ?? '');
    $dbPass = (string) ($_POST['db_pass'] ?? '');
    $appUrl = rtrim(trim($_POST['app_url'] ?? ''), '/');
    $adminName  = trim($_POST['admin_name'] ?? 'Administrator');
    $adminEmail = trim($_POST['admin_email'] ?? '');
    $adminPass  = (string) ($_POST['admin_pass'] ?? '');

    if ($dbName === '' || $dbUser === '')           $errors[] = 'Database name and user are required.';
    if (!filter_var($appUrl, FILTER_VALIDATE_URL))  $errors[] = 'A valid application URL is required.';
    if (!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) $errors[] = 'A valid admin email is required.';
    if (strlen($adminPass) < 8)                      $errors[] = 'Admin password must be at least 8 characters.';

    $pdo = null;
    if ($errors === []) {
        try {
            $pdo = new PDO("mysql:host={$dbHost};dbname={$dbName};charset=utf8mb4", $dbUser, $dbPass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ]);
        } catch (PDOException $e) {
            $errors[] = 'Database connection failed: ' . $e->getMessage();
        }
    }

    if ($errors === [] && $pdo) {
        try {
            // 1. Import schema.
            $sql = file_get_contents(ROOT . '/database/schema.sql');
            $pdo->exec($sql);

            // 2. Set the admin account from the form.
            $hash = password_hash($adminPass, PASSWORD_DEFAULT);
            $stmt = $pdo->prepare(
                "INSERT INTO users (name,email,password,role,is_verified,plan_id)
                 VALUES (?,?,?, 'admin', 1, (SELECT id FROM plans WHERE slug='agency' LIMIT 1))
                 ON DUPLICATE KEY UPDATE name=VALUES(name), password=VALUES(password), role='admin', is_verified=1"
            );
            $stmt->execute([$adminName, strtolower($adminEmail), $hash]);

            // Remove the default seeded admin if a different email was chosen.
            if (strtolower($adminEmail) !== 'admin@eventogen.com') {
                $pdo->prepare("DELETE FROM users WHERE email='admin@eventogen.com'")->execute();
            }

            // 3. Write config/config.php.
            $appKey  = bin2hex(random_bytes(16));
            $cronKey = bin2hex(random_bytes(12));
            $config  = render_config($dbHost, $dbName, $dbUser, $dbPass, $appUrl, $appKey, $cronKey);
            file_put_contents(ROOT . '/config/config.php', $config);

            // 4. Lock the installer.
            file_put_contents(LOCK, date('c'));

            $done = true;
            $doneCronKey = $cronKey;
            $doneUrl = $appUrl;
        } catch (\Throwable $e) {
            $errors[] = 'Installation error: ' . $e->getMessage();
        }
    }
}

function render_config(string $h, string $n, string $u, string $p, string $url, string $key, string $cron): string
{
    $esc = static fn ($v) => addslashes((string) $v);
    return <<<PHP
<?php
/**
 * Eventogen Mailer - Application configuration (generated by installer).
 */

declare(strict_types=1);

define('APP_NAME', 'Eventogen Mailer');
define('APP_ENV',  'production');

define('APP_URL', getenv('APP_URL') ?: '{$esc($url)}');

define('BASE_PATH', dirname(__DIR__));
define('UPLOAD_PATH', BASE_PATH . '/uploads');

define('DB_HOST', getenv('DB_HOST') ?: '{$esc($h)}');
define('DB_NAME', getenv('DB_NAME') ?: '{$esc($n)}');
define('DB_USER', getenv('DB_USER') ?: '{$esc($u)}');
define('DB_PASS', getenv('DB_PASS') ?: '{$esc($p)}');
define('DB_CHARSET', 'utf8mb4');

define('APP_KEY',  getenv('APP_KEY')  ?: '{$esc($key)}');
define('CRON_KEY', getenv('CRON_KEY') ?: '{$esc($cron)}');

define('BATCH_SIZE', 25);          // emails processed per cron run
define('MAX_ATTEMPTS', 3);         // retries before marking failed
define('SEND_DELAY_MS', 250);      // micro-delay between sends (ms)

// Google Sign-In (OAuth 2.0) - optional, blank disables the button.
define('GOOGLE_CLIENT_ID', getenv('GOOGLE_CLIENT_ID') ?: '');
define('GOOGLE_CLIENT_SECRET', getenv('GOOGLE_CLIENT_SECRET') ?: '');

if (APP_ENV === 'development') {
    error_reporting(E_ALL);
    ini_set('display_errors', '1');
} else {
    error_reporting(E_ALL & ~E_DEPRECATED & ~E_NOTICE);
    ini_set('display_errors', '0');
}

date_default_timezone_set('Asia/Kolkata');

PHP;
}
?><!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Install · Eventogen Mailer</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
<style>
  :root { --brand: #6d5efc; --brand-600: #5b4ee8; }
  body { font-family: "Montserrat", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    background: linear-gradient(135deg, #6d5efc 0%, #8b5cf6 55%, #a855f7 100%); min-height: 100vh; }
  .card { border: 0; border-radius: 16px; }
  .btn-primary { background: var(--brand); border-color: var(--brand); }
  .btn-primary:hover { background: var(--brand-600); border-color: var(--brand-600); }
  .form-control:focus { border-color: var(--brand); box-shadow: 0 0 0 .25rem rgba(109,94,252,.18); }
  a { color: var(--brand); }
</style>
</head>
<body class="py-5">
<div class="container" style="max-width:680px">
  <div class="text-center text-white mb-4">
    <h1 class="fw-bold"><i class="bi bi-send-fill"></i> Eventogen Mailer</h1>
    <p class="opacity-75">Installation Wizard</p>
  </div>

  <div class="card shadow">
    <div class="card-body p-4">
    <?php if ($done): ?>
      <div class="text-center">
        <div class="text-success" style="font-size:3rem"><i class="bi bi-check-circle-fill"></i></div>
        <h3>Installation complete!</h3>
        <p class="text-muted">Your platform is ready. Sign in with the admin account you just created.</p>
        <a href="<?= htmlspecialchars($doneUrl) ?>/login" class="btn btn-primary btn-lg mt-2">Go to login</a>
        <div class="alert alert-warning text-start mt-4 small">
          <strong>Set up your cron jobs</strong> (Hostinger → Advanced → Cron Jobs):
          <pre class="mb-1 mt-2">*/5 * * * * php <?= htmlspecialchars(realpath(ROOT)) ?>/cron/send-emails.php</pre>
          <pre class="mb-0">*/15 * * * * php <?= htmlspecialchars(realpath(ROOT)) ?>/cron/automations.php</pre>
          <hr>
          Your <strong>CRON_KEY</strong> (for URL-based cron) is: <code><?= htmlspecialchars($doneCronKey) ?></code>
          <br>Delete the <code>/install</code> folder now for security.
        </div>
      </div>
    <?php else: ?>
      <h4 class="mb-3">System requirements</h4>
      <ul class="list-group mb-4">
        <?php foreach ($checks as $label => $ok): ?>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <?= htmlspecialchars($label) ?>
            <?php if ($ok): ?><span class="badge bg-success"><i class="bi bi-check"></i> OK</span>
            <?php else: ?><span class="badge bg-danger"><i class="bi bi-x"></i> Missing</span><?php endif; ?>
          </li>
        <?php endforeach; ?>
      </ul>

      <?php if (!$canInstall): ?>
        <div class="alert alert-danger">Please resolve the failing requirements above, then reload this page.</div>
      <?php else: ?>
        <?php foreach ($errors as $err): ?><div class="alert alert-danger py-2"><?= htmlspecialchars($err) ?></div><?php endforeach; ?>
        <form method="post">
          <h5 class="mt-2">Database</h5>
          <div class="row g-2 mb-3">
            <div class="col-md-6"><label class="form-label small">DB host</label><input class="form-control" name="db_host" value="<?= htmlspecialchars($_POST['db_host'] ?? 'localhost') ?>"></div>
            <div class="col-md-6"><label class="form-label small">DB name</label><input class="form-control" name="db_name" value="<?= htmlspecialchars($_POST['db_name'] ?? '') ?>" required></div>
            <div class="col-md-6"><label class="form-label small">DB user</label><input class="form-control" name="db_user" value="<?= htmlspecialchars($_POST['db_user'] ?? '') ?>" required></div>
            <div class="col-md-6"><label class="form-label small">DB password</label><input type="password" class="form-control" name="db_pass"></div>
          </div>

          <h5>Application</h5>
          <div class="mb-3"><label class="form-label small">Public URL (no trailing slash)</label>
            <input class="form-control" name="app_url" placeholder="https://mailer.yourdomain.com" value="<?= htmlspecialchars($_POST['app_url'] ?? '') ?>" required></div>

          <h5>Admin account</h5>
          <div class="row g-2 mb-3">
            <div class="col-md-6"><label class="form-label small">Name</label><input class="form-control" name="admin_name" value="<?= htmlspecialchars($_POST['admin_name'] ?? 'Administrator') ?>"></div>
            <div class="col-md-6"><label class="form-label small">Email</label><input type="email" class="form-control" name="admin_email" value="<?= htmlspecialchars($_POST['admin_email'] ?? '') ?>" required></div>
            <div class="col-md-12"><label class="form-label small">Password (min 8 chars)</label><input type="password" class="form-control" name="admin_pass" required minlength="8"></div>
          </div>

          <button class="btn btn-primary btn-lg w-100"><i class="bi bi-gear"></i> Install Eventogen Mailer</button>
        </form>
      <?php endif; ?>
    <?php endif; ?>
    </div>
  </div>
</div>
</body>
</html>
