-- ---------------------------------------------------------------------
--  Deliverability: domain authentication (SPF/DKIM/DMARC), platform DKIM
--  signing, and reputation-based auto-throttle. Run once on an existing
--  database (new installs get this via schema.sql).
-- ---------------------------------------------------------------------

-- Sending domains a user has added and (optionally) verified. Each domain
-- gets its own DKIM keypair generated by the platform; the private key is
-- used to sign outgoing mail regardless of which SMTP relay carries it.
CREATE TABLE IF NOT EXISTS `domains` (
  `id`               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id`          BIGINT UNSIGNED NOT NULL,
  `domain`           VARCHAR(190)    NOT NULL,
  `dkim_selector`    VARCHAR(60)     NOT NULL,
  `dkim_private_key` TEXT            NOT NULL,   -- encrypted at rest (Crypto)
  `dkim_public_key`  TEXT            NOT NULL,   -- raw base64, for the DNS TXT record
  `spf_verified`     TINYINT(1)      NOT NULL DEFAULT 0,
  `dkim_verified`    TINYINT(1)      NOT NULL DEFAULT 0,
  `dmarc_verified`   TINYINT(1)      NOT NULL DEFAULT 0,
  `is_verified`      TINYINT(1)      NOT NULL DEFAULT 0,  -- SPF + DKIM both pass; DMARC recommended but not required
  `last_checked_at`  DATETIME        DEFAULT NULL,
  `created_at`       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_domains_user_domain` (`user_id`,`domain`),
  CONSTRAINT `fk_domains_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Link a sending account to a verified domain (opt-in: NULL = no domain gate,
-- keeps existing accounts working unchanged) and per-account webhook identity
-- + reputation-driven auto-pause bookkeeping.
ALTER TABLE `smtp_accounts`
  ADD COLUMN `domain_id`      BIGINT UNSIGNED DEFAULT NULL AFTER `group_id`,
  ADD COLUMN `webhook_token`  VARCHAR(64)     DEFAULT NULL AFTER `last_checked`,
  ADD COLUMN `auto_paused_at` DATETIME        DEFAULT NULL AFTER `webhook_token`,
  ADD COLUMN `pause_reason`   VARCHAR(255)    DEFAULT NULL AFTER `auto_paused_at`,
  ADD KEY `idx_smtp_domain` (`domain_id`),
  ADD UNIQUE KEY `uq_smtp_webhook_token` (`webhook_token`),
  ADD CONSTRAINT `fk_smtp_domain` FOREIGN KEY (`domain_id`) REFERENCES `domains`(`id`) ON DELETE SET NULL;

-- Backfill a webhook token for existing accounts so the UI can show a
-- webhook URL immediately without a separate migration step.
UPDATE `smtp_accounts` SET `webhook_token` = SUBSTRING(MD5(RAND()), 1, 32) WHERE `webhook_token` IS NULL;

-- Bounce sub-type (hard = permanent, soft = transient) so reputation math can
-- weight them differently, and a 'complained' event for spam-complaint
-- webhooks (SES/Mailgun/SendGrid/Brevo).
ALTER TABLE `email_logs`
  MODIFY COLUMN `event` ENUM('sent','failed','bounced','complained') NOT NULL,
  ADD COLUMN `bounce_type` ENUM('hard','soft') DEFAULT NULL AFTER `event`;
